export const FEATURE_FLAGS = {
  KNOWLEDGE_AGENT_ENABLED: true,
  DOCUMENT_UPLOAD_ENABLED: true,
  BASIC_AUTH_ENABLED: true,
  MULTI_TENANT_ENABLED: true,
  ANALYTICS_DASHBOARD_ENABLED: true,
  PROJECT_AGENT_ENABLED: true,
  SLACK_WEBHOOK_ENABLED: true,
  EMAIL_WEBHOOK_ENABLED: false,
  CONFIDENCE_ESCALATION_ENABLED: true,
  SLACK_QA_ENABLED: true,
  DOCUMENT_RBAC_ENABLED: true,
  SSO_ENABLED: true,
  CONNECTOR_SYNC_ENABLED: true,
  EVALUATION_DASHBOARD_ENABLED: true,
  TICKET_APPROVAL_ENABLED: true,
  INTEGRATIONS_SETTINGS_ENABLED: true,
  JIRA_INTEGRATION_ENABLED: true,
  DEMO_TENANT_ENABLED: true,
  RETRIEVAL_TRACE_ENABLED: true,
  WORKLOAD_BALANCING_ENABLED: true,
} as const;

export type FeatureFlag = keyof typeof FEATURE_FLAGS;
